version: '3.8'

services:
  app:
    image: docker.io/library/car-showroom:latest
    environment:
      - DB_USER=postgres
      - DB_NAME=CarShowroom
      - DB_PASSWORD=zeyis16
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=CarShowroom
      - POSTGRES_PASSWORD=zeyis16
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
